blueshift-gg/blueshift-dashboard

src/app/content/challenges/anchor-vault/en/challenge.mdx
src/app/content/courses/spl-token-with-web3js/introduction/en.mdx
src/app/content/courses/token-2022-with-anchor/introduction/en.mdx

- Fix relative link (leading to 404 error) 
- Fix typo `chagne` to `change`
- Fix typo `InterfaceAccounts` to `InterfaceAccount`

fix: links and typo

---

src/app/content/courses/spl-token-with-web3js/introduction/en.mdx

wrong example code for token account generation

fix: wrong example code

---

src/app/content/courses/token-2022-program/introduction/en.mdx
src/app/content/courses/token-2022-program/token-extensions/en.mdx

Some sentences are copies of sentences a little above. Also fixed couple of typos

fix: doubled sentences in token-2022-program course

---

src/app/components/TableOfContents/TableOfContents.tsx

Substr has been deprecated and it is recommended to use substring or slice. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr#browser_compatibility

fix: replace deprecated substr with substring

---

src/app/content/courses/introduction-to-pinocchio/pinocchio-accounts/en.mdx

`AccountCheck` trait was implemented for `SignerAccount` and `SystemAccount` with illegal `pub` visibility modifier, in the **Introduction to Pinocchio** course.
remove `pub` visibility modifiers from the trait implementation
cc @dhl

fix: impl `AccountCheck` trait in the Introduction to Pinocchio course

---

src/app/content/challenges/anchor-escrow/en/pages/make.mdx

Added warning about SPL Token-2022 risks in escrow logic.
Content :
Certain extensions from SPL Token-2022 e.g., transfer hooks, confidential transfers, default account states can introduce vulnerabilities like blocking transfers , locking funds and causing rug pulls in escrow logic, vaults, or CPIs.
- Ensure `mint_a` and `mint_b` are owned by the same token program to prevent CPI failures.
- Use well-audited tokens (e.g., USDC, wSOL) from the standard SPL Token program.
- Avoid unverified or complex Token-2022 mints. 
reference : https://www.solana-program.com/docs/token-2022/extensions#example-creating-a-mint-with-default-frozen-accounts .

feat:  add T22 warning to Anchor Escrow  #27

---

src/app/content/courses/program-security/arbitrary-cpi/en.mdx
src/app/content/courses/program-security/data-matching/en.mdx
src/app/content/courses/program-security/owner-checks/en.mdx
src/app/content/courses/program-security/reinitialization-attacks/en.mdx
src/app/content/courses/program-security/revival-attacks/en.mdx
src/app/content/courses/program-security/signer-checks/en.mdx
src/app/content/courses/program-security/type-cosplay/en.mdx

The example provided to verify matching discriminators doesn't actually work. Here's my take on it. Feedbacks are welcomed!

fix: typo and incorrect discriminator example [program-security]

---

src/app/content/challenges/pinocchio-flash-loan/en/pages/borrow.mdx
src/app/content/challenges/pinocchio-flash-loan/en/pages/repay.mdx

1. `new_unchecked` that is used to get instructions does not check if the provided data is from the Sysvar Account. Added the check to `try_from` for `LoanAccounts`
2. When creating `LoanData` balance in taken from borrower's account. If a borrower has 0 tokens then `balance_with_fee` will also be zero, and the chech in repay will always succeed -  a borrower does not need to return anything. Changed to protocol's account
3. Added `drop(loan_data)` before closing account. Without it the drop will happen after the account is closed, which is probably UB, not sure
4. Small optimization. There is no need to manually zero out lamports in the loan account because it is done in the `close_unchecked` function

fix: several things in pinocchio-flash-loan challenge

---

src/app/content/courses/token-2022-program/introduction/en.mdx

Token account length is 165 bytes. Account type is in byte 166. Also account type for `Mint` is 1 and for `Token` is 2

fix: token account length in token-2022-program course

---

src/app/[locale]/[...slug]/page.tsx
src/app/[locale]/not-found.tsx

1. **Challenge routes showing wrong button**: When you visited `/challenges/xyz` (invalid challenge), it was showing "Head to Courses" button instead of "Head to Challenges"
2. **Root routes using Next.js default error**: Routes like `/en/zysd` were showing the default Next.js error page instead of our custom 404 page
- Added a catch-all route `[...slug]` to handle invalid paths properly
- Made the 404 page smart - it now shows the right button based on what you were trying to access
- Fixed the layout so all 404 pages use our custom design
| Before | After |
|--------|-------|
| ![Wrong button on challenges/xyz](https://github.com/user-attachments/assets/ae54e6b2-4898-4544-8fc6-b28fc029af7d) | ![Corrected button on /challenges/xyz](https://github.com/user-attachments/assets/dc31645a-e779- …

fix: add catch-all route for custom 404 page

---

src/app/content/courses/testing-with-mollusk/mollusk-101/en.mdx

fixes typo

---

src/app/content/courses/introduction-to-pinocchio/reading-and-writing-data/en.mdx

The section about dynamic data currently shows a message about being more challenging to work with `Vec` and `String` types when using pinocchio due to it being a `no_std` crate. The message is not accurate since the fact that pinocchio is a `no_std` crate does not affect the program.
For a program to be `no_std`, it will have to explicitly declare its crate to be `no_std`.
Remove the message since there are no differences in working with dynamic data when using pinocchio.

Remove message about pinocchio

---

src/app/content/courses/testing-with-mollusk/mollusk-101/en.mdx
src/app/content/courses/testing-with-mollusk/mollusk-101/fr.mdx

Avoid manually moving the dependencies to the dev-dependencies section
Mollusk introduction course manually requires devs to add dependencies
to the `dev-dependencies` section of their `Cargo.toml` file yet they
are already using `cargo add` to add dependencies.
This commit adds a `--dev` flag to each `cargo add <crate-name>` to automatically
add each dependency to the `dev` section of the manifest file.
This add the information to the french course too
Depends on PR #137 since it incorporates a fix from that PR
Closes #138

Use dev cargo args in mollusk course

---

src/app/content/challenges/assembly-memo/en/challenge.mdx
src/app/content/challenges/assembly-memo/en/verify.mdx
src/app/content/challenges/assembly-slippage/en/challenge.mdx
src/app/content/challenges/assembly-slippage/en/verify.mdx
src/app/content/challenges/assembly-timeout/en/verify.mdx

Links on the verify pages to the tooling were broken and registry looked like a typo

links and typo fixes

---

src/app/content/challenges/anchor-escrow/en/pages/make.mdx

Small text-only edits in the Make section to improve clarity and grammar.
•	Clarify the note about passing a single token_program.
•	Fix a couple of minor phrasing/typo issues.

Minor copy edits for clarity

---

src/app/content/courses/token-2022-with-web3js/default-account-state-extension/en.mdx
src/app/content/courses/token-2022-with-web3js/default-account-state-extension/fr.mdx
src/app/content/courses/token-2022-with-web3js/default-account-state-extension/vi.mdx
src/app/content/courses/token-2022-with-web3js/default-account-state-extension/zh-CN.mdx

Added incorrect instructions to the transaction. 
The correct instruction to add should have been initializeDefaultAccountState, but initializeMintCloseAuthority was incorrectly added instead. initializeMintCloseAuthority does not exist.

fix: Replace initializeMintCloseAuthority with initializeDefaultAccountState

---

src/app/content/courses/introduction-to-assembly/assembly-101/en.mdx
src/app/content/courses/introduction-to-assembly/instructions/en.mdx
src/app/content/courses/introduction-to-assembly/program-example/en.mdx
src/app/content/courses/introduction-to-assembly/registers-and-memory/en.mdx

1. Changes in memory layout table:
- Updated the description of the stack region: it is not 32 KiB, but 4 × 64 KiB. Also removed “grows downward” since it could be misinterpreted as the stack growing below the 0x200000000 address.
- Removed the mention of `sol_alloc_free`, as it was removed some time ago.
2. Changed `;` to `#` in couple of places
3. Some typos and formatting

fix: several things in introduction-to-assembly course

---

src/app/[locale]/layout.tsx
src/app/components/Challenges/ClientChallengeTable.tsx
src/app/components/Challenges/ProgramChallengeTable.tsx
src/app/globals.css
src/app/mdx-layout.tsx

Geist Mono and other beautiful mono space fonts do not have proper monospace alignment, making some of the ASCII drawings and listings difficult to read:
Change to Fira Code

feat: improve code block readability

---

src/app/content/challenges/pinocchio-flash-loan/de/pages/borrow.mdx
src/app/content/challenges/pinocchio-flash-loan/en/pages/borrow.mdx
src/app/content/challenges/pinocchio-flash-loan/fr/pages/borrow.mdx
src/app/content/challenges/pinocchio-flash-loan/id/pages/borrow.mdx
src/app/content/challenges/pinocchio-flash-loan/uk/pages/borrow.mdx
src/app/content/challenges/pinocchio-flash-loan/vi/pages/borrow.mdx
src/app/content/challenges/pinocchio-flash-loan/zh-CN/pages/borrow.mdx
src/app/content/challenges/pinocchio-flash-loan/zh-HK/pages/borrow.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/de.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/en.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/fr.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/id.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/uk.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/vi.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/zh-CN.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/zh-HK.mdx
src/app/content/courses/program-security/duplicate-mutable-accounts/de.mdx
src/app/content/courses/program-security/duplicate-mutable-accounts/en.mdx
src/app/content/courses/program-security/duplicate-mutable-accounts/fr.mdx
src/app/content/courses/program-security/duplicate-mutable-accounts/id.mdx
src/app/content/courses/program-security/duplicate-mutable-accounts/uk.mdx
src/app/content/courses/program-security/duplicate-mutable-accounts/vi.mdx
src/app/content/courses/program-security/duplicate-mutable-accounts/zh-CN.mdx
src/app/content/courses/program-security/duplicate-mutable-accounts/zh-HK.mdx

`pinocchio` content uses not recommended way of comparison `Pubkey`s
actualize content to use https://github.com/anza-xyz/pinocchio/pull/248 because it was published in [v0.9.2](https://github.com/anza-xyz/pinocchio/releases/tag/pinocchio%40v0.9.2)
cc @dhl

refactor: use `pubkey_eq` in pinocchio

---

src/app/content/courses/instruction-introspection/introspection-with-pinocchio/de.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/en.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/fr.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/id.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/uk.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/vi.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/zh-CN.mdx
src/app/content/courses/instruction-introspection/introspection-with-pinocchio/zh-HK.mdx

**pinocchio**s section of `instruction-introspection` course has obsolete information
actualize the section (imports, api, etc)
cc @dhl

fix: actualize instruction introspection for pinocchio
